[workspace]

members = ["curvature", "data-block", "data-block-benches"]
default-members = ["curvature", "data-block"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Yjy"]
keywords = ["query-engine", "arrow"]

[workspace.dependencies]
snafu = "0.7.5"
paste = "1.0.14"
libc = "0.2"
regex = "1.10.2"
either = "1.9"
bitvec = "1.0"


[profile.release]
lto = true
