[package]
name = "curvature"
version.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-block = { path = "../data-block" }
snafu = { workspace = true, features = ["rust_1_61"] }
quanta = { workspace = true }

[dev-dependencies]
expect-test = "1.4.1"

[features]
profile = []
